name: Build CI

# Controls when the workflow will run
on:
  [push]
jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 11.0.18+10
        cache: 'maven'
    - name: Build with Maven
      run: mvn -B install --file pom.xml
    - name: Generate jacoco report
      run: mvn --file pom.xml --batch-mode --update-snapshots test jacoco:report
    - name: Coveralls GitHub Action
      run: mvn --file pom.xml coveralls:report --define repoToken=${{ secrets.COVERALLS_REPO_TOKEN }}
